### ISSUE TITLE
Virtual environment in Windows 10

### ISSUE THREAD

**Issue by lucianolorenti** [jpy-consortium/jpy#101]
Hi!
I am trying to use the library to call some python code from java, but I want to use a python virtual environment I have. I am using windows. I wrote:
```java
        PyLib.setPythonHome("C:\\Users\\LucianoLorenti\\venvs\\general310\\");
        PyLib.setProgramName("python310.exe"); // I also tried with python.exe (both exists)
        PyLib.startPython();
```     
I am setting the PythonHome to the base path to the virtual environment and the name of the executable  but I am getting:

  ```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
  Python runtime state: core initialized
  ModuleNotFoundError: No module named 'encodings'
  
  Current thread 0x00002bf0 (most recent call first):
    <no Python frame>
```

If I don't set the  `setPythonHome` I don't have this error, and the library is initialized but I assume is using the python of the system.

What am  I doing wrong? How can I specify the path to my virtual env?

thank you!

**Comment by devinrsmith** [comment]
@lucianolorenti, can you try:

```java
        PyLib.setProgramName("C:\\Users\\LucianoLorenti\\venvs\\general310\\bin\\python310.exe");
        PyLib.startPython();
```

or, whatever the full path to your python venv exe is.
