### ISSUE TITLE
jpy-0.13.0.jar empty ?

### ISSUE THREAD

**Issue by edu-de** [jpy-consortium/jpy#102]
the jpy-0.13.0.jar file is empty here: https://github.com/jpy-consortium/jpy/releases/tag/v0.13.0
no classes, only some directories. In maven the file is correct...

**Comment by devinrsmith** [comment]
Thanks for pointing this out. I'll get it fixed right away, replaced with https://repo.maven.apache.org/maven2/org/jpyconsortium/jpy/0.13.0/jpy-0.13.0.jar.

**Comment by devinrsmith** [comment]
Fixed, thanks!
