### ISSUE TITLE
Does jpy available in maven central repository?

### ISSUE THREAD

**Issue by abhikt48** [jpy-consortium/jpy#15]
I tried to find below library in maven central repo, but it's not available. Could you please tell suggest repository location to download below dependency? Or do we need to build locally and use it? Please suggest.

```
<dependency>
	<groupId>org.jpy</groupId>
	<artifactId>jpy</artifactId>
	<version>0.9.0</version>
</dependency>
```

**Comment by jmao-denver** [comment]
Hi, I would suggest either try this - a build by Deephaven Data Labs based on a fork of JPY with many enhancements  or simply build locally. 

```
<dependency>
    <groupId>io.deephaven</groupId>
    <artifactId>deephaven-jpy</artifactId>
    <version>0.10.0</version>
</dependency>
```

**Comment by niloc132** [comment]
We are also going to need to manage the fact that the domain `jpy.org` is not available (at least not for a reasonable price...), so the groupId should change to match whatever is selected instead, and in turn, the package structure should likely change as well.

**Comment by devinrsmith** [comment]
jpy is now available under the `org.jpyconsortium` group id at maven central.

https://search.maven.org/search?q=g:org.jpyconsortium
