### ISSUE TITLE
Question: Is "Beta" tag intentional?

### ISSUE THREAD

**Issue by vyadh** [jpy-consortium/jpy#174]
According to the [setup.py](https://github.com/jpy-consortium/jpy/blob/master/setup.py#L374) information, and therefore in PyPI, this package is stated as being "beta" in its lifecycle. Since this is a long running actively maintained project can I asked whether this is intentional? Particularly as I don't see this anywhere else in the docs. The company I work for needs to make decisions about what packages we use and for all intents and purposes, this project looks pretty high quality. However, the beta label makes it at little problematic to be able to use it. It would be really helpful if we could understand if it's actually intentional or not - I wondered whether it was just an historical quirk that it's not been updated. Much appreciate any info!

**Comment by devinrsmith** [comment]
Hi @vyadh.

I do not consider jpy as "beta"; I'm one of the primary maintainers for it, and we use have been using it in production at https://github.com/deephaven for a many years. I know there are other companies using it in production settings.

I will bring this up with the team and we can probably get this updated to `Development Status :: 5 - Production/Stable`.

Thanks for reaching out!
