### ISSUE TITLE
Unsatisfied Link Error

### ISSUE THREAD

**Issue by hadfield** [jpy-consortium/jpy#97]
I'm getting the following error when trying to start up Python within Java:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/hadfield/Local/external-git/jpy/build/lib.macosx-11.1-arm64-3.9/jpy.cpython-39-darwin.so: dlopen(/Users/hadfield/Local/external-git/jpy/build/lib.macosx-11.1-arm64-3.9/jpy.cpython-39-darwin.so, 0x0001): symbol not found in flat namespace (_PyBool_Type)

Error: symbol not found in flat namespace (_PyBool_Type)

This is on an M1 Mac.

Everything compiles ok with:
`python setup.py build maven
`
and the whl builds ok with:
`python setup.py build bdist_wheel
`
Using Python 3.9, switched to Python 3.8 and got the same error message.

My java is:
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-macos-aarch64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-macos-aarch64) (build 25.332-b09, mixed mode)

The compile commands look like:
`clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -I/opt/homebrew/anaconda3/include -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -Isrc/main/c -I/Users/hadfield/.jenv/versions/zulu64-1.8.0.332/include -I/Users/hadfield/.jenv/versions/zulu64-1.8.0.332/include/darwin -I/opt/homebrew/anaconda3/include/python3.9 -c src/main/c/jni/org_jpy_PyLib.c -o build/temp.macosx-11.1-arm64-3.9/src/main/c/jni/org_jpy_PyLib.o
`

Any suggestions or ideas to help diagnose the issue?

**Comment by devinrsmith** [comment]
Setting the java system property `-Djpy.debug=true` may provide a bit more debugging information; I'm happy to take a look at your initialization logic as well.

It looks like your java is keying off of your jpy build directory - it may be advisable to use the wheel and install it into a virtual environment instead. The relevant properties can be found https://github.com/jpy-consortium/jpy/blob/v0.13.0/src/main/java/org/jpy/PyLibConfig.java#L37-L41.

**Comment by hadfield** [comment]
Thanks.  I set the debug flag, installed the wheel and switched to that but get the same error message:

org.jpy.PyLib: entered static initializer
org.jpy.PyLibConfig: entered static initializer
org.jpy.PyLibConfig: exited static initializer
org.jpy.PyLib: System.load("/opt/homebrew/anaconda3/lib/python3.9/site-packages/jpy.cpython-39-darwin.so")
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/homebrew/anaconda3/lib/python3.9/site-packages/jpy.cpython-39-darwin.so: dlopen(/opt/homebrew/anaconda3/lib/python3.9/site-packages/jpy.cpython-39-darwin.so, 0x0001): symbol not found in flat namespace (_PyBool_Type)


the exception is thrown when trying to do:
PyLib.isPythonRunning()

The full exception is:
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/homebrew/anaconda3/lib/python3.9/site-packages/jpy.cpython-39-darwin.so: dlopen(/opt/homebrew/anaconda3/lib/python3.9/site-packages/jpy.cpython-39-darwin.so, 0x0001): symbol not found in flat namespace (_PyBool_Type)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at org.jpy.PyLib.loadLib(PyLib.java:508)
	at org.jpy.PyLib.<clinit>(PyLib.java:567)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:65)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:65)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:162)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at ai.haley.model.chain.test.TestPythonBridge.main(TestPythonBridge.groovy:57)

**Comment by hadfield** [comment]
wheel was built and installed via:
python setup.py build maven bdist_wheel
pip install dist/jpy-0.14.0.dev0-cp39-cp39-macosx_11_0_arm64.whl

that put files directly into site-packages rather than a subdirectory like "jpy"
ls -lah /opt/homebrew/anaconda3/lib/python3.9/site-packages/
-rw-r--r--     1 hadfield  staff    45K Jan 25 05:46 jpy-0.14.0-SNAPSHOT.jar
drwxr-xr-x    10 hadfield  staff   320B Jan 25 05:46 jpy-0.14.0.dev0.dist-info
-rwxr-xr-x     1 hadfield  staff   180K Jan 25 05:46 jpy.cpython-39-darwin.so
-rw-r--r--     1 hadfield  staff   515B Jan 25 05:57 jpyconfig.properties
-rw-r--r--     1 hadfield  staff   380B Jan 25 05:46 jpyconfig.py
-rw-r--r--     1 hadfield  staff    26K Jan 25 05:46 jpyutil.py

but this seems unrelated to the link error.

**Comment by hadfield** [comment]
I'm not super familiar with inspecting symbols in the library, but if I do this:
nm -gC /opt/homebrew/anaconda3/lib/python3.9/site-packages/jpy.cpython-39-darwin.so | grep Bool
00000000000217c8 S _JPy_Boolean_BooleanValue_MID
00000000000217b8 S _JPy_Boolean_JClass
00000000000217c0 S _JPy_Boolean_ValueOf_SMID
0000000000021588 S _JPy_JBoolean
00000000000215d0 S _JPy_JBooleanObj
0000000000010a4c T _JType_ConvertPyArgToJBooleanArg
000000000000d6c0 T _JType_CreateJavaBooleanObject
0000000000010a1c T _JType_MatchPyArgAsJBooleanParam
0000000000011848 T _JType_MatchVarArgPyArgAsJBooleanParam
00000000000062fc T _Java_org_jpy_PyLib_getBooleanValue
00000000000065f4 T _Java_org_jpy_PyLib_pyBoolCheck
                 U _PyBool_FromLong
                 U _PyBool_Type
                 

The "U" appears to mean undefined for the symbol "_PyBool_Type".

Does that mean some other library defining that symbol should be present and isn't?

**Comment by hadfield** [comment]
I see older issues that seem related like:
https://github.com/bcdev/jpy/issues/108
but not a solution.

**Comment by devinrsmith** [comment]
Question: are you modifying jpy? If not, it may be preferable to use the binary wheel / maven central JAR. We have M1 builds for 3.8, 3.9, 3.10, and 3.11 (https://pypi.org/project/jpy/#files).

I think from the java side though, there is probably a missing piece of configuration. Are you setting the java system property `jpy.pythonLib`?

Can you run the following snippet from your python virtual environment:

```python
import sys
import jpyutil

jpy_properties = {
    'jpy.pythonPrefix': sys.prefix,
    'jpy.programName': sys.executable,
    'jpy.pythonLib': jpyutil._find_python_dll_file(fail=False),
    'jpy.jpyLib': jpyutil._get_module_path('jpy', fail=False),
    'jpy.jdlLib': jpyutil._get_module_path('jdl', fail=False)
}

jpy_properties_format = '\n'.join([ '{}={}'.format(key, value) for key, value in jpy_properties.items() ])

print(jpy_properties_format)
```

It may also be useful to run the snippet with the environment variable `JPY_LOG_LEVEL` set to `DEBUG`

**Comment by hadfield** [comment]
I installed the whl: jpy-0.13.0-cp39-cp39-macosx_12_0_arm64.whl 

and ran the script you provided, which ran.

I used the values from that back into the Java side
(and did NOT set PYTHONHOME as an environmental value, which was mentioned in some of the prior Issues)

And that did run successfully.

A simple script completed:

```	
println "Running: " + PyLib.isPythonRunning()
PyLib.startPython()
PyModule sys1 = PyModule.importModule("sys")
final long sys1Pointer = sys1.getPointer()
println "Pointer: " + sys1Pointer
PyLib.stopPython()
```

I think there was something wrong with the build and the pythonLib may not have been set correctly, but my immediate issue is solved.  I can compare my local build with the whl at some point and report any problem specific to that, if any.

Thanks for your help!

**Comment by hadfield** [comment]
I was working off the installation documentation here:
https://jpy.readthedocs.io/en/latest/install.html

which says:

> The jpy Java API requires a maximum of two configuration parameters:
> 
> jpy.jpyLib - path to the ‘jpy’ Python module, namely the jpy.so (Unix) or jpy.pyd (Windows) file
> jpy.jdlLib - path to the ‘jdl’ Python module, namely the jpy.so (Unix) file. Not used on Windows.
> 

And does not mention the jpy.pythonLib property.  So, I would recommend updating the documentation to include that.

**Comment by devinrsmith** [comment]
You're welcome - thank _you_ for taking the time to file and follow through on your issue.

I agree, we should update that documentation. I'll cross-link to https://github.com/jpy-consortium/jpy/issues/9 to remind us to update docs wrt jpy.pythonLib.
